name: Update CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/flake-cache-action@main
        with:
          token: ${{ secrets.FLAKEHUB_AUTH_TOKEN }}

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.PATww }}
